language: cpp
env:
  global:
  - QT_FATAL_WARNINGS=1
  - SHADOW_BUILD_DIR=/tmp/shadow_build_dir

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    env: SPEC=linux-g++-64 QT_PATH=/opt/qt57 QT_VER=57
    sudo: required
before_install:
- sudo add-apt-repository --yes ppa:beineri/opt-qt571-trusty
- sudo apt-get update -qq
install:
  - if [ "${SPEC}" = "linux-g++-64" ]; then 
      sudo apt-get install clang libgl1-mesa-dev qt${QT_VER}base qt${QT_VER}script qt${QT_VER}qbs qt${QT_VER}serialport &&
      export PATH=$QT_PATH/bin:$PATH &&
      echo $PATH &&
      which qmake && 
      which qbs &&
      qbs config defaultProfile qt5 &&
      qbs setup-toolchains --detect && 
      qbs setup-qt $QT_PATH/bin/qmake qt5 && 
      qbs config --list profiles 
      ;
    fi

script:
- mkdir ${SHADOW_BUILD_DIR} && cd ${SHADOW_BUILD_DIR}
- qbs --file ${TRAVIS_BUILD_DIR}/attitude-feeder.qbs release
- cp $QT_PATH/lib/libQt5Core.so.5 release/install-root
- cp $QT_PATH/lib/libQt5Network.so.5 release/install-root
- cp $QT_PATH/lib/libQt5SerialPort.so.5 release/install-root
- ldconfig -p | grep icu
- cp /usr/lib/x86_64-linux-gnu/libicudata.so.52 release/install-root
- cp /usr/lib/x86_64-linux-gnu/libicui18n.so.52 release/install-root
- cp /usr/lib/x86_64-linux-gnu/libicuuc.so.52 release/install-root
- mv release/install-root/attfeeder release/install-root/.attfeeder.bin
- cp ${TRAVIS_BUILD_DIR}/.attfeeder release/install-root/attfeeder
- if [ -n "${TRAVIS_TAG}" ]; then 
    VER=`echo $TRAVIS_TAG | sed -r "s/v?(.*)/\1/"` &&
    echo $VER &&
    export VER &&
    mv release/install-root attfeeder-linux-x64 &&
    tar -cjSf attfeeder-linux-x64-${VER}.tar.bz2 attfeeder-linux-x64 &&
    ls &&
    pwd
    ;
  fi
 
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
  - "${SHADOW_BUILD_DIR}/attfeeder-linux-x64-${VER}.tar.bz2"
  skip_cleanup: true
  on:
    tags: true
